channels:
- conda-forge
dependencies:
- python=3.11.2
- pip<=24.2
- pip:
  - dagshub==0.5.1
  - mlflow==3.4.0
  - cloudpickle==3.1.0
  - numpy==1.26.6
  - pandas==2.1.4
  - psutil==5.9.0
  - scikit-learn==1.6.0
  - scipy==1.14.1
name: mlflow-env
